#pragma once

enum JOB		{ WORRIOR = 1, MAGICIAN, THIEF};
enum MAIN_MENU	{ FIELD = 1, UPGRADE, EXIT};
enum FIELD_MENU {MAP1 = 1, MAP2, MAP3, PREV};
enum FIGHT_MENU {ATTACK = 1, ESCAPE};
enum ANSWER {YES = 1, NO};
enum UPGRADE_MAIN {DAMADGE = 1, HEALTH};